### ISSUE TITLE
"No characteristic was found" error

### ISSUE THREAD

**Issue by dnicolson** [futomi/node-switchbot#1]
When communicating with a SwitchBot device I received a characteristic error, I was able to successfully communicate with it by removing the device UUID check:
https://github.com/futomi/node-switchbot/blob/202044a6c48fa5149c5d25a3adba1ec14b20c1ac/lib/switchbot-device.js#L190

I'm wondering if it's necessary to check for the _CHAR_UUID_DEVICE value:
https://github.com/futomi/node-switchbot/blob/202044a6c48fa5149c5d25a3adba1ec14b20c1ac/lib/switchbot-device.js#L27

As when I query `discoverAllServicesAndCharacteristics` on the peripheral, I don't get `2a00` but get the following UUIDs:
```
fec8
fec7
fec9
cba20003224d11e69fb80002a5d5c51b
cba20002224d11e69fb80002a5d5c51b
```

**Comment by futomi** [comment]
I got the following UUIDs from my Bot:

```
2a00
2a01
2a04
fec8
fec7
fec9
cba20003224d11e69fb80002a5d5c51b
cba20002224d11e69fb80002a5d5c51b
```

It seems that there is a model which does not support `0x2a00`. I wonder there are differences depending on when it is manufactured or which country it is sold...

Anyway, I updated this module so that the `0x2a00` is optional. Try the latest version of this module (v0.0.3). You can use the npm to install the latest version.

Thank you.

**Comment by dnicolson** [comment]
Thanks for the quick fix, it works now.
